apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: testCA
  template:
    metadata:
      labels:
        app: testCA
    spec:
      nodeSelector:
        intent: apps
      containers:
        - name: testCA
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
              memory: 1.5Gi
