apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: event-cr
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - nodes
  - services
  - persistentvolumeclaims
  verbs:
  - list
  - watch
