apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpe
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cpe
  template:
    metadata:
      labels:
        app: cpe
    spec:
      containers:
      - name: cpe
        image: ACCOUNTID.dkr.ecr.us-east-1.amazonaws.com/ECR_REPO_URI:TAG
