apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpe
  labels:
    app: cpe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpe        
  template:
    metadata:
      labels:
        app: cpe
    spec:
      containers:
      - name: cpe
        image: $ACCOUNTID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO
